# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0002_auto_20180305_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zhihu.Topic'),
        ),
    ]
